# Generated by Django 3.2.7 on 2021-09-28 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.address'),
        ),
    ]
