# Generated by Django 3.2.7 on 2021-10-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210929_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts_where_this_product', to='myapp.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='unique_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
