# Generated by Django 3.2.7 on 2021-10-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
