# Generated by Django 3.2.7 on 2021-10-09 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20211010_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
        ),
    ]
