# Generated by Django 3.2.7 on 2021-10-19 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeruser',
            name='address',
        ),
        migrations.DeleteModel(
            name='SellerUser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.DeleteModel(
            name='BuyerUser',
        ),
    ]
