# Generated by Django 3.2.7 on 2021-10-10 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20211010_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_of', to='myapp.address'),
        ),
    ]
