# Generated by Django 3.2.7 on 2021-10-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_auto_20211012_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeruser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='address_of', to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='company_address_of', to='myapp.address'),
        ),
    ]
