# Generated by Django 3.2.7 on 2021-10-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartline',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cartlines', to='myapp.cart'),
        ),
    ]
