# Generated by Django 3.2.7 on 2021-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_cartline_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeruser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
