# Generated by Django 3.2.7 on 2021-10-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20211017_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
