# Generated by Django 3.2.7 on 2021-10-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20211017_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_first_name',
            new_name='billing_firstname',
        ),
    ]
