# Generated by Django 3.2.7 on 2021-10-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_rename_billing_first_name_order_billing_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_last_name',
            new_name='billing_lastname',
        ),
    ]
