# Generated by Django 3.2.7 on 2021-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unique_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
